# This file was copied from the following URL and modified:
# https://github.com/golangci/golangci-lint-action/blob/master/README.md#how-to-use

name: golangci
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    # TODO: move matrix to go-test workflow/job
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        platform: [ubuntu-latest, macos-latest]
    # TODO: change to ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          # TODO: change to 1.19.x
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.0 # current version at time of commit
      # TODO: move this to separate workflow/job
      - name: go-test
        run: go test ./...
